/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proj;

/**
 *
 * @author Kushal
 */
public class SensorData extends javax.swing.JFrame {

    /**
     * Creates new form Controls
     */
    public SensorData() {
        initComponents();
    }
String sall;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Temprature = new javax.swing.JButton();
        Light = new javax.swing.JButton();
        Proximity = new javax.swing.JButton();
        Motion = new javax.swing.JButton();
        CTF = new javax.swing.JTextField();
        Back = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1063, 749));
        jPanel1.setLayout(null);

        Temprature.setBackground(new java.awt.Color(0, 0, 0));
        Temprature.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Temprature.setForeground(new java.awt.Color(255, 255, 255));
        Temprature.setText("Temperature");
        Temprature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TempratureActionPerformed(evt);
            }
        });
        jPanel1.add(Temprature);
        Temprature.setBounds(200, 200, 150, 49);

        Light.setBackground(new java.awt.Color(0, 0, 0));
        Light.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Light.setForeground(new java.awt.Color(255, 255, 255));
        Light.setText("Light");
        Light.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LightActionPerformed(evt);
            }
        });
        jPanel1.add(Light);
        Light.setBounds(200, 350, 139, 49);

        Proximity.setBackground(new java.awt.Color(0, 0, 0));
        Proximity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Proximity.setForeground(new java.awt.Color(255, 255, 255));
        Proximity.setText("Proximity");
        Proximity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProximityActionPerformed(evt);
            }
        });
        jPanel1.add(Proximity);
        Proximity.setBounds(740, 210, 148, 49);

        Motion.setBackground(new java.awt.Color(0, 0, 0));
        Motion.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Motion.setForeground(new java.awt.Color(255, 255, 255));
        Motion.setText("Motion");
        Motion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MotionActionPerformed(evt);
            }
        });
        jPanel1.add(Motion);
        Motion.setBounds(750, 360, 149, 49);

        CTF.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CTF.setForeground(new java.awt.Color(0, 102, 255));
        jPanel1.add(CTF);
        CTF.setBounds(180, 450, 740, 170);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj/proj images/Arrow-Left-icon.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(0, 2, 49, 25);

        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj/proj images/home-20.png"))); // NOI18N
        jPanel1.add(Home);
        Home.setBounds(56, 0, 53, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proj/proj images/bg2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 20, 1090, 640);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TempratureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TempratureActionPerformed
CTF.setText("Temperature is ");        // TODO add your handling code here:
 //sall=CTF.getText()+"\n";

    }//GEN-LAST:event_TempratureActionPerformed

    private void MotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MotionActionPerformed
       CTF.setText("Motion ");
       sall=CTF.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_MotionActionPerformed

    private void ProximityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProximityActionPerformed
       CTF.setText("Proximity ");
       sall=CTF.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_ProximityActionPerformed

    private void LightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LightActionPerformed
      CTF.setText("Light");
      sall=CTF.getText();
        // TODO add your handling code here:
    }//GEN-LAST:event_LightActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
Main m=new Main();
m.setVisible(true);
dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JTextField CTF;
    private javax.swing.JButton Home;
    private javax.swing.JButton Light;
    private javax.swing.JButton Motion;
    private javax.swing.JButton Proximity;
    private javax.swing.JButton Temprature;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
